### ISSUE TITLE
Issue with LogOut confirmation

### ISSUE THREAD

**Issue by anhadarora** [ashwinikumar01/Flutter-Firebase#1]
The logout button does not show a confirmation dialog. It just keeps the page as is.

On refreshing the page in a web app, only the circular progress indicator shows, and a hot restart is required to get to the sign in page again.

**Comment by ashwinikumar01** [comment]
@anhadarora 
<img src="https://user-images.githubusercontent.com/69667369/98021668-9740d400-1e2a-11eb-9d92-cb908ad5159d.jpg" width="300" height="500" />
I think there's no issue with that part and regarding the sign in part ,there's not error with that.
Check once again and inform me.It's working properly and user is remained in the application.
